### ISSUE TITLE
There is a bug in using powerJoinWhereHas with array callback

### ISSUE THREAD

**Issue by Ham3D** [kirschbaum-development/eloquent-power-joins#118]
there is a bug in this case, Argument #6 ($callback) must be of type ?Closure, array given

```
User::powerJoinWhereHas('commentsThroughPosts', [
    'comments' => fn ($query) => $query->where('body', 'a')
])->get());
```

**Comment by beshoo** [comment]
Please can you send a PL, with test?

**Comment by Ham3D** [comment]
we have two nested relations on the Items model.

models:

- Items
- Items2
- Items3

`Items -> Items2 -> Items3
`

```
$items = Items::query();
$items->powerJoinWhereHas('items2.items3', [
    'items3Table' => fn ($query) => $query->where('id', 1),
]);
```

this query results in this Exception:

`TypeError : App\Models\BaseModel::scopeHasNestedUsingJoins(): Argument #6 ($callback) must be of type ?Closure, array given, called in`

**Comment by Ham3D** [comment]
check this line:

https://github.com/kirschbaum-development/eloquent-power-joins/blob/master/src/PowerJoins.php#L318

**Comment by beshoo** [comment]
Yes, fix the problem and sed PL with the test

**Comment by luisdalmolin** [comment]
Definitely open to Pull Requests with fixes, with tests included. Honestly, I recommend using the regular `whereHas` in this case. The `powerJoinWhereHas` feature might get removed in the next major version of this package. I'm closing the issue since we may not actively work to fix something that will likely get removed.
