### ISSUE TITLE
Usage without traits possible?

### ISSUE THREAD

**Issue by tpaksu** [kirschbaum-development/eloquent-power-joins#24]
Hello, 

I have a package that accepts model classes to create tables for it, but when it comes to sorting and filtering, it needs joins instead of relationship instances. But since the classes are dynamic and given from outside world, I don't have the chance to extend the model classes with traits. I can do it with using eval, but it's not recommended, and will not work in most servers, it's not an option. So I need to use PowerJoins trait methods without the trait... 

Is it somehow possible? For example 

```php
$model = PowerJoins::joinRelationship($model, ["related1", "related2"]);
```

Thanks.

**Comment by luisdalmolin** [comment]
Version 1 didn't need a trait and you just had access to the available methods. It had some issues that were not solvable though, and because of this, we moved to a trait-based approach.

If you want, you can try with version 1.0, it should work in most of the cases. I can take a look at this when I have some time, but the short answer is you need the trait in version 2 for now.

**Comment by tpaksu** [comment]
Thank you for your fast response, I couldn't respond earlier as I was outside, I solved my need with a simple function which gets the relationship data from belongsTo etc. method outputs ( table name, foreign key and local key) and simply adds a join to the query. Seems enough for now. Thanks again.
