### ISSUE TITLE
Use relation collections

### ISSUE THREAD

**Issue by jaulz** [kirschbaum-development/eloquent-power-joins#56]
First of all: thanks for this cool library! 😊 

Right now, I'm scratching my head because when I do the join all the data is retrieved correctly but all attributes are stored in the attributes of the model (even foreign attributes). Is it somehow possible to store the retrieved data automatically in the corresponding relations?

So after using `$post->joinRelationship('user')->get()` I want to be able to use `$post->user`. Is that even possible?
Thanks!

**Comment by luisdalmolin** [comment]
@jaulz No, that's not currently possible, I think you will be better of accomplishing this using eager loading instead of joins, in this case.

This would be very complex and probably not worth implementing here since it would be doing the same as eager loading, and it would only work for 1-1 relationships.

**Comment by jaulz** [comment]
Thanks for the really quick answer! Do you know by any chance if there is a package which could accomplish that?

**Comment by luisdalmolin** [comment]
Default Laravel should be able to do that. You can do:

```php
Post::with('user')->get();
```
