### ISSUE TITLE
BelongsToMany with relatedKey

### ISSUE THREAD

**Issue by simong88** [kirschbaum-development/eloquent-power-joins#79]
Hi,

PowerJoins does not work with belongToMany when we use custom related key (6th parameter), for example : 
` return $this->belongsToMany("\App\Models\Material", "CUSTOMER_MATERIAL", "CUSTNO", "CARNO", "CUSTNO", "CARNO");`

Generated query is :
`select * from [CUSTOMER] left join [CUSTOMER_MATERIAL] on [CUSTOMER_MATERIAL].[CUSTNO] = [CUSTOMER].[CUSTNO] left join [MATERIAL] on [MATERIAL].[IDMaterial] = [CUSTOMER_MATERIAL].[CARNO]`
Should be : 
`select * from [CUSTOMER] left join [CUSTOMER_MATERIAL] on [CUSTOMER_MATERIAL].[CUSTNO] = [CUSTOMER].[CUSTNO] left join [MATERIAL] on [MATERIAL].[CARNO] = [CUSTOMER_MATERIAL].[CARNO]`

I think line 108 in RelationshipsExtraMethods.php should be: 
`"{$this->getModel()->getTable()}.{$this->getRelatedKeyName()}",`

**Comment by luisdalmolin** [comment]
Are you sure about this? Can you describe your current table structure and also give an example on how you are calling the join relationship method?

**Comment by beshoo** [comment]
> PowerJoins does not work with belongToMany when we use custom related key (6th parameter), for example : ` return $this->belongsToMany("\App\Models\Material", "CUSTOMER_MATERIAL", "CUSTNO", "CARNO", "CUSTNO", "CARNO");`
> 
> Generated query is : `select * from [CUSTOMER] left join [CUSTOMER_MATERIAL] on [CUSTOMER_MATERIAL].[CUSTNO] = [CUSTOMER].[CUSTNO] left join [MATERIAL] on [MATERIAL].[IDMaterial] = [CUSTOMER_MATERIAL].[CARNO]` Should be : `select * from [CUSTOMER] left join [CUSTOMER_MATERIAL] on [CUSTOMER_MATERIAL].[CUSTNO] = [CUSTOMER].[CUSTNO] left join [MATERIAL] on [MATERIAL].[CARNO] = [CUSTOMER_MATERIAL].[CARNO]`
> 
> I think line 108 in RelationshipsExtraMethods.php should be: `"{$this->getModel()->getTable()}.{$this->getRelatedKeyName()}",`

It looks like you are trying to use the belongsToMany method in Laravel's Eloquent ORM with a custom related key, but it's not producing the expected query.

The belongsToMany method allows you to define a many-to-many relationship between two models, and it takes several parameters to define the relationship. The sixth parameter is the foreign key name in the intermediate table for the model on which the belongsToMany method is called. In your example, you are using "CUSTNO" as the foreign key name.

Based on the generated query you provided, it looks like the belongsToMany method is using the correct foreign key name in the intermediate table. However, the issue seems to be with the join condition for the MATERIAL table. The generated query is using [MATERIAL].[IDMaterial] = [CUSTOMER_MATERIAL].[CARNO], but you expected it to be [MATERIAL].[CARNO] = [CUSTOMER_MATERIAL].[CARNO].

To fix this issue, you can specify the custom related key for the MATERIAL model by passing it as the fifth parameter to the belongsToMany method. This will cause the belongsToMany method to use the correct key in the join condition for the MATERIAL table.

Here's an example of how you can do this:


```
return $this->belongsToMany("\App\Models\Material", "CUSTOMER_MATERIAL", "CUSTNO", "CARNO", "CUSTNO", "CARNO")
            ->using("\App\Models\CustomerMaterial")
            ->withPivot("CARNO");
```
I hope this helps! Let me know if you have any question

**Comment by luisdalmolin** [comment]
Thanks @beshoo - Closing this issue for now. If it's still an issue, let me know

**Comment by kadirgun** [comment]
I have same issue.

```sql
INNER JOIN `accountings` ON `accountings`.`id` = `accounting_transactions`.`accounting_id`
LEFT JOIN `accounting_transaction_cargo` AS `cargos_pivot` ON `cargos_pivot`.`accounting_transaction_id` = `accounting_transactions`.`id`
LEFT JOIN `cargos` AS `cargos` ON `cargos`.`id` = `cargos_pivot`.`process_number`
```

must be

```sql
INNER JOIN `accountings` ON `accountings`.`id` = `accounting_transactions`.`accounting_id`
LEFT JOIN `accounting_transaction_cargo` AS `cargos_pivot` ON `cargos_pivot`.`accounting_transaction_id` = `accounting_transactions`.`id`
LEFT JOIN `cargos` AS `cargos` ON `cargos`.`process_number` = `cargos_pivot`.`process_number`
```

My Relation function is like this.

```php
public function cargos()
{
    return $this->belongsToMany(
        Cargo::class,
        'accounting_transaction_cargo',
        'accounting_transaction_id',
        'process_number',
        "id",
        "process_number",
    );
}
```

With this query I can get cargos without any problem.
```php
AccountingTransaction::with('cargos')->first();
```

`relatedKey` and `parentKey` seem to switch places.
